//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialCounHistory = new HashSet<MaterialCounHistory>();
            this.StorageMaterial = new HashSet<StorageMaterial>();
            this.SupplierHistory = new HashSet<SupplierHistory>();
            this.UsedMaterial = new HashSet<UsedMaterial>();
        }
    
        public int MaterialID { get; set; }
        public int MaterialTypeID { get; set; }
        public string MaterialName { get; set; }
        public int MaterialCountInPack { get; set; }
        public string MaterialUnitMeasure { get; set; }
        public string MaterialDescription { get; set; }
        public string MaterialImage { get; set; }
        public decimal MaterialCost { get; set; }
        public int MaterialQuantityInStock { get; set; }
        public int MaterialMinCount { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialCounHistory> MaterialCounHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageMaterial> StorageMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierHistory> SupplierHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedMaterial> UsedMaterial { get; set; }
    }
}
