//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCounHistory
    {
        public int MaterialCounHistoryID { get; set; }
        public int MaterialID { get; set; }
        public int MaterialCounHistoryValue { get; set; }
        public System.DateTime MaterialCounHistoryDate { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
