//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartnerProductSale = new HashSet<PartnerProductSale>();
            this.ProductCostHistory = new HashSet<ProductCostHistory>();
            this.PointSale = new HashSet<PointSale>();
        }
    
        public int PartnerID { get; set; }
        public int CompanyTypeID { get; set; }
        public string PartnerCompanyName { get; set; }
        public string PartnerDirSurame { get; set; }
        public string PartnerDirName { get; set; }
        public string PartnerDirPatronymic { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerPhone { get; set; }
        public string PartnerIndex { get; set; }
        public string PartnerRegion { get; set; }
        public string PartnerCity { get; set; }
        public string PartnerStreet { get; set; }
        public string ParnterBuildNumber { get; set; }
        public string PartnerINN { get; set; }
        public int PartnerRating { get; set; }
        public string PartnerLogo { get; set; }
    
        public virtual CompanyType CompanyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProductSale> PartnerProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCostHistory> ProductCostHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointSale> PointSale { get; set; }

        public string PartnerType
        {
            get
            {
                return CompanyType.CompanyType1;
            }
        }

        public int PartnerDiscount
        {
            get
            {
                int total = 0;
                foreach (PartnerProductSale productSales in this.PartnerProductSale)
                {
                    total += productSales.PartnerProductSaleCount * Convert.ToInt32(productSales.Product.ProductCost);
                }

                int sale = 0;

                if (total > 10000 && total < 50000)
                {
                    sale = 5;
                }
                else if (total > 50000 && total < 300000)
                {
                    sale = 10;
                }
                else if (total > 300000)
                {
                    sale = 15;
                }

                return sale;
            }
        }
    }
}
