//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductSale
    {
        public int PartnerProductSaleID { get; set; }
        public string ProductArticle { get; set; }
        public int PartnerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int PartnerProductSaleCount { get; set; }
        public System.DateTime PartnerProductSaleDate { get; set; }
        public Nullable<decimal> PartnerProductCost { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
