//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PartnerProductSale = new HashSet<PartnerProductSale>();
            this.ProductCostHistory = new HashSet<ProductCostHistory>();
            this.StorageProduct = new HashSet<StorageProduct>();
            this.UsedMaterial = new HashSet<UsedMaterial>();
        }
    
        public string ProductArticle { get; set; }
        public int ProductTypeID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<int> UsedMaterialsID { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public Nullable<int> ProductPackLengthMm { get; set; }
        public Nullable<int> ProductPackHeightMm { get; set; }
        public Nullable<int> ProductPackWidthMm { get; set; }
        public Nullable<decimal> ProductPackWeightKg { get; set; }
        public string ProductQualityCertificate { get; set; }
        public string ProductStandartNumber { get; set; }
        public Nullable<decimal> ProductProductionTimeHour { get; set; }
        public Nullable<decimal> ProductFirstCost { get; set; }
        public string ProductWorkshopNumber { get; set; }
        public Nullable<int> ProductPeopleCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProductSale> PartnerProductSale { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCostHistory> ProductCostHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageProduct> StorageProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedMaterial> UsedMaterial { get; set; }
    }
}
