//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCostHistory
    {
        public int ProductCostHistoryID { get; set; }
        public int PartnerID { get; set; }
        public string ProductArticle { get; set; }
        public decimal ProductCostHistoryMinCost { get; set; }
        public System.DateTime ProductCostHistoryDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
