//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FloorMasterEntities : DbContext
    {
        private static FloorMasterEntities _context;
        public static FloorMasterEntities GetContext()
        {
            if (_context == null)
            {
                _context = new FloorMasterEntities();
            }
            return _context;
        }
        public FloorMasterEntities()
            : base("name=FloorMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionOrOutput> AdmissionOrOutput { get; set; }
        public virtual DbSet<CompanyType> CompanyType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialCounHistory> MaterialCounHistory { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<PartnerProductSale> PartnerProductSale { get; set; }
        public virtual DbSet<PointSale> PointSale { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCostHistory> ProductCostHistory { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StorageMaterial> StorageMaterial { get; set; }
        public virtual DbSet<StorageProduct> StorageProduct { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierHistory> SupplierHistory { get; set; }
        public virtual DbSet<UsedMaterial> UsedMaterial { get; set; }
    }
}
