//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageProduct
    {
        public int StorageProductID { get; set; }
        public string ProductArticle { get; set; }
        public int StorageProductCount { get; set; }
        public System.DateTime StorageProductDate { get; set; }
        public int AdmissionOrOutput { get; set; }
    
        public virtual AdmissionOrOutput AdmissionOrOutput1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
