//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovMasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierHistory
    {
        public int SupplierHistorySaleID { get; set; }
        public int SupplierID { get; set; }
        public int MaterialID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int SupplierHistoryProdCount { get; set; }
        public System.DateTime SupplierHistoryDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Material Material { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
